name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

      - name: build
        run: |
            ./build.sh
            if [ ! -f "./build/bin/rtype-client" ]; then
                echo "rtype-client is not here"
                exit 1
            fi
            if [ ! -f "./build/bin/rtype-tcp-server" ]; then
                echo "rtype-tcp-server is not here"
                exit 1
            fi
            if [ ! -f "./build/bin/rtype-udp-server" ]; then
                echo "rtype-udp-server is not here"
                exit 1
            fi
            find ./src -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -print0 | xargs -0 clang-format -i
        shell: bash